name: flutter_capture_vision_platform_interface
description: Common platform interface and typed contracts for flutter_capture_vision.
version: 0.1.0
resolution: workspace

environment:
  sdk: ^3.10.0
  flutter: '>=3.38.0'

dependencies:
  plugin_platform_interface: ^2.1.8

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
